### ISSUE TITLE
[sleepyyj] TODO List

### ISSUE THREAD

**Issue by sleepyyj** [WhiteMatrixTech/graphql-microservice-demo#8]
### Description

1、分页resolver处理除分页参数以外的请求参数
2、去除NodeItem节点，Response跟Github的API保持一致

### Proposed solution

- [x] Apollo Gateway
    - [x] Authorization
- [x] Prisma Schema / Client 
    - (参考 baas-dao 项目，各 service 共用，demo 中用相对路径引用即可，不用发包)
- [x] User Service
    - [x] Authentication
- [x] Resovation Service

--- 

GraphQL：
- [x] Server
    - [x] SDL Specification 统一的定义，参考 Github GraphQL API v4 每一个 connection 都需要有各自单独的定义
    - [x] Resolver 支持带 connection 的嵌套查询
- [x] Testing
    - [x] Integration testing with coverage
    - [x] Memory Database
